### ISSUE TITLE
coulm width

### ISSUE THREAD

**Issue by Dontorpedo** [icetalker/filament-table-repeater#12]
can you add a columnsSpan functionality ? or something to change the width of the columns

**Comment by jadersilvabr** [comment]
did you find a workaround?

**Comment by Congminh7799** [comment]
> can you add a columnsSpan functionality ? or something to change the width of the column
Did you find a solution to the problem?

**Comment by Congminh7799** [comment]
> can you add a columnsSpan functionality ? or something to change the width of the columns

Did you find a solution to the problem?

**Comment by Congminh7799** [comment]
> did you find a workaround?

And you?

**Comment by icetalker** [comment]
New feature for this has been added. use `colStyles()` to pass the css style of the cell you would like to customize. See the use case in README.md for details. Thanks for your support!

**Comment by qcol** [comment]
I'm trying to make the text right-aligned and colStyles not working. It turns out that it only works for TH headers so width works correctly (TH forces width), but text-align only works for the TH header.
