### ISSUE TITLE
Unable to install in Laravel 10.3.3

### ISSUE THREAD

**Issue by michael-mhrdd** [icetalker/filament-table-repeater#17]
When installing in Laravel 10, I get the following error:

Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - icetalker/filament-table-repeater[v0.1.0, ..., v0.1.5] require illuminate/contracts ^8.6|^9.0 -> found illuminate/contracts[v8.6.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires icetalker/filament-table-repeater * -> satisfiable by icetalker/filament-table-repeater[v0.1.0, ..., v0.1.5].

**Comment by icetalker** [comment]
Fixed. Check the latest version.
