### ISSUE TITLE
colStyles not applied on component cells

### ISSUE THREAD

**Issue by codetoon** [icetalker/filament-table-repeater#30]
Hi

Thanks for the wonderful plugin

In the following snippet colStyles is not applied on the component columns.

```php

 TableRepeater::make('contribution_items')
                    ->relationship('contribution_items')
                    ->schema([

                        Forms\Components\Select::make('accounting_head_id')
                            ->label('Item')

                            ->options(..)

                            ->required(),
                        Forms\Components\TextInput::make('amount')
                            ->label('Amount')

                            ->required(),

                    ])                    
                    ->colStyles(['accounting_head_id' => 'padding-top:5px; padding-bottom:2px;', 'amount' => 'padding-top:5px; padding-bottom:2px;'])
```

The reason for this bug the `$colStyles` variable is not wrapped in the curly braces in the `table-repeater.blade.php` file

![image](https://github.com/icetalker/filament-table-repeater/assets/147634/18b1975e-0b7e-4626-89b7-dff3ec307f8a)

I have fixed the bug  and it appears to work fine now. Do you accept pull requests for bug fixes? @icetalker

**Comment by icetalker** [comment]
PR for such kind of fix will be welcome. Anyway,I've fixed that while adding laravel 11 support lately. Thank you for your information!
